name: Design Tokens Update
on:
  repository_dispatch:
    types: [update-tokens, test-event, design-tokens, tokens]  # Support multiple event types
jobs:
  process-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FIGMA_GITHUB_TOKEN || github.token }}
        
      - name: Print event details
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
          
      - name: Process design tokens
        if: github.event.action == 'update-tokens'
        run: |
          echo "Processing design tokens from Figma..."
          echo "Filename: ${{ github.event.client_payload.filename }}"
          echo "Commit message: ${{ github.event.client_payload.commitMessage }}"
          
          # Create tokens directory if it doesn't exist
          mkdir -p src/tokens/figma-export
          
          # Check if tokens are provided in client_payload
          if [ -n "${{ github.event.client_payload.tokens }}" ]; then
            echo "📦 Tokens provided in payload"
            
            # Check if tokens are compressed
            if [ "${{ github.event.client_payload.compressed }}" = "true" ]; then
              echo "🔧 Decompressing tokens..."
              echo '${{ github.event.client_payload.tokens }}' | base64 -d | gunzip > src/tokens/figma-export/design-tokens.json
              echo "✅ Tokens decompressed successfully"
            else
              echo "📄 Tokens are uncompressed"
              echo '${{ github.event.client_payload.tokens }}' > src/tokens/figma-export/design-tokens.json
            fi
          else
            echo "⚠️ No tokens in payload - payload might be too large"
            echo "Creating placeholder file for large payload handling"
            echo '{"note": "Payload too large for GitHub dispatch", "filename": "${{ github.event.client_payload.filename }}", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > src/tokens/figma-export/design-tokens.json
          fi
          
          # Validate and pretty print the JSON
          if jq empty src/tokens/figma-export/design-tokens.json 2>/dev/null; then
            echo "✅ Valid JSON received from Figma"
            jq '.' src/tokens/figma-export/design-tokens.json > src/tokens/figma-export/design-tokens-formatted.json
          else
            echo "⚠️ Invalid JSON received, saving raw content"
            cp src/tokens/figma-export/design-tokens.json src/tokens/figma-export/design-tokens-formatted.json
          fi
          
      - name: Commit and push changes
        if: github.event.action == 'update-tokens'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/tokens/figma-export/
          git commit -m "Update design tokens from Figma: ${{ github.event.client_payload.commitMessage }}" || exit 0
          git push