name: Dispatch Trigger
on:
  repository_dispatch:
    types: [test-event]  # Must match the event_type sent to /dispatches
jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: echo "Triggered with payload ${{ github.event.client_payload }}"